# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NeuStockApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NeuStockApp
  pod "SwiftSpinner"
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
end
